name: ondeindia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  dio: ^4.0.4
  http: ^0.13.4
  lottie: ^2.7.0
  location: ^5.0.3
  ionicons: ^0.2.2
  line_icons: ^2.0.1
  geolocator: ^10.1.0
  fluttertoast: ^8.0.8
  flutter_share: ^2.0.0
  url_launcher: ^6.0.20
  flutter_switch: ^0.3.2
  pin_code_fields: ^8.0.1
  cupertino_icons: ^1.0.2  
  show_up_animation: ^2.0.0
  google_maps_flutter: ^2.1.1
  flutter_zoom_drawer: ^2.3.1
  flutter_polyline_points: ^1.0.0
  simple_ripple_animation: ^0.0.3
  # platform_device_id: ^1.0.1
  firebase_messaging: ^14.7.9
  firebase_core: ^2.24.2
  flutter_local_notifications: ^16.2.0
  shared_preferences: ^2.0.15
  email_validator: ^2.0.1
  awesome_dialog: ^3.1.0
  geocoding: ^2.0.4
  expandable_bottom_sheet: ^1.1.1+1
  image_picker: ^1.0.5
  flutter_html: ^3.0.0-beta.2
  # flutter_credit_card_new: ^0.0.4
  google_place: ^0.4.7
  flutter_dotenv: ^5.0.2
  google_places_flutter: ^2.0.5
  uuid: ^4.2.2
  # spinner_date_time_picker: ^0.0.8
  custom_info_window: ^1.0.1
  razorpay_flutter: ^1.3.0
  syncfusion_flutter_datepicker: ^20.2.40
  intl: ^0.18.1
  jiffy: ^5.0.0
  custom_clippers: ^2.0.0
  firebase_crashlytics: ^3.4.8
  get: ^4.6.5
  ftoast: ^2.0.0
  firebase_auth: ^4.15.3
  group_button: ^5.3.4
  # otp_timer_button: ^1.1.0
  flutter_cache_manager: ^3.3.0
  flutter_rating_stars: ^1.0.3+4
  flutter_easyloading: ^3.0.5
  marquee_vertical: ^1.0.0
  upgrader: ^8.4.0
  # flutter_datetime_picker: ^1.5.1
  flutter_datetime_picker_plus: ^2.1.0
  contacts_service: ^0.6.3
  mobile_number: ^2.1.1
  telephony: ^0.2.0
  otp: ^3.1.3
  mobile_number_picker: ^0.0.1+5
  flutter_phone_direct_caller: ^2.1.1
  device_info_plus: ^9.1.1
  account_picker: ^2.1.0
  sim_data: ^0.0.2
  sms_autofill: ^2.3.0
  permission_handler: ^11.0.1
  url_launcher_ios: ^6.2.1
  package_info_plus: ^4.2.0
  calendar_date_picker2: ^0.5.5
  action_slider: ^0.7.0
  flutter_upgrade_version: ^1.1.1
  in_app_update: ^4.2.0
  change_app_package_name: ^1.2.0
  # sms_otp_auto_verify: ^2.1.0
  # sms: ^0.2.4
  # sms_otp_auto_verify: ^2.1.0
  # package_info_plus: ^1.4.2
  # permission_handler: ^10.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/cabs/
    - assets/shapes/
    - assets/mainpics/
    - assets/animation/
    - assets/vehicles/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MonR
      fonts:
        # - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Inter-Regular.ttf
    - family: MonB
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        # - asset: assets/fonts/Montserrat-Bold.ttf
    - family: MonM
      fonts:
        # - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Inter-Medium.ttf
    - family: MonBlack
      fonts:
        # - asset: assets/fonts/Montserrat-Black.ttf
        - asset: assets/fonts/Inter-Black.ttf
    - family: MonS
      fonts:
        # - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: MonL
      fonts:
        # - asset: assets/fonts/Montserrat-Light.ttf                    
        - asset: assets/fonts/Inter-Light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages